---
project_repo: https://github.com/onecloud/neutron.git
project_branch: icehouse_reorg
migration_project_repo: https://github.com/onecloud/l3-asr-migration.git
ncclient_repo: https://github.com/jon-wei/ncclient.git
asr1k_a: 10.1.10.252
asr1k_b: 10.1.10.253
